# This workflow will back-merge master -> staging -> edge after merging
# a pull request to master.
#
# Actions used in this workflow:
# https://github.com/actions/checkout
#

name: Backmerge master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  post-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            This is an automated release created by GitHub actions.
          draft: false
          prerelease: false
      - name: Run post-release script
        run: .github/bin/post-release patch
